name: CI

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify script signature
        shell: pwsh
        run: |
          Write-Host "Checking RandomMAC.ps1 signature"
          $sig = Get-AuthenticodeSignature -FilePath .\RandomMAC.ps1
          Write-Host "Signature status: $($sig.Status)"
          if ($sig.Status -ne 'Valid') { Write-Error "Signature not valid: $($sig.Status)"; exit 1 }

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser -Repository PSGallery -AllowClobber
          $diag = Invoke-ScriptAnalyzer -Path .\RandomMAC.ps1 -Recurse
          if ($diag | Where-Object { $_.Severity -eq 'Error' }) {
            $diag | Where-Object { $_.Severity -eq 'Error' } | Format-Table -AutoSize
            Write-Error 'PSScriptAnalyzer found Errors'
            exit 1
          }
