name: CI

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check script signature (warning)
        shell: pwsh
        run: |
          Write-Host "Checking RandomMAC.ps1 signature (will warn but not fail CI)"
          $sig = Get-AuthenticodeSignature -FilePath .\RandomMAC.ps1
          Write-Host "Signature status: $($sig.Status)"
          if ($sig.Status -ne 'Valid') { Write-Warning "Signature not valid: $($sig.Status)" }

      - name: Validate config
        shell: pwsh
        run: |
          Write-Host "Validating randomMAC.config.json"
          .\test-validate-config.ps1

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser -Repository PSGallery -AllowClobber
          $settings = Join-Path $PSScriptRoot 'PSScriptAnalyzer.Settings.psd1'
          $diag = Invoke-ScriptAnalyzer -Path .\RandomMAC.ps1 -Recurse -Settings $settings
          if ($diag | Where-Object { $_.Severity -eq 'Error' }) {
            $diag | Where-Object { $_.Severity -eq 'Error' } | Format-Table -AutoSize
            Write-Error 'PSScriptAnalyzer found Errors'
            exit 1
          }
